### ISSUE TITLE
Single Serving: Rubric Task List

### ISSUE THREAD

**Issue by jgagne** [jtexX/New-to-gaming#1]
# Single Serving
## Rubric Task List

5 tasks (`20 points` each) with 1 extra credit task.

### Best Practices

`100 points`

- [x] Mobile-first and friendly
  - Use of a mobile-first, single-column layout for small screens, with a `max-width` and centered layout for wider screens.
- [ ] Optimize all images
  - [Squoosh](https://squoosh.app): Use `MozJPEG` to optimize JPGs and use `OptiPNG` to optimize PNGs. (You may resize an image in Squoosh as well if needed.)
  - [ImageOptim](https://imageoptim.com/mac): Enable all image optimizations options (specifically `Guetzli`) via `ImageOptim` > `Preferences…` > `Enable` (left sidebar in General settings).
  - *Note:* Aim for an optimized file size around `150 KB` and below (max `200 KB`).
- [ ] Validate all HTML, CSS, and color contrast
  - [Validate HTML](https://validator.w3.org/nu/) (No errors; warnings are ok, but try to resolve.)
  - [Validate CSS](http://jigsaw.w3.org/css-validator/) (No errors; warnings are ok, but try to resolve.)
  - [Color Contrast Accessibility Validator](https://color.a11y.com/) (All color combinations should pass: *Congratulations! No automated color contrast issues found on the webpage tested.*)
- [ ] Audit performance, accessibility, best practices, and SEO of all pages.
  - [Measure](https://web.dev/measure/) and score 92 or above in all four categories.
- [x] Add a *description* and *URL* to the About section of your GitHub repo.
  - Share URL in `04-single-serving` channel
  - Repo should contain only essential files, and remember to use lowercase naming:
    - `index.html`
    - `css` (folder containing an external stylesheet)
      - For example: `main.css`
    - `img` (folder containing images)
      - For example: `self-portrait.jpg`
    - `README.md`
      - Update with a proper heading (title) and paragraph (description) using [Markdown](https://www.markdownguide.org/basic-syntax/).

### Extra Credit

`20 points`

- [ ] Use of single (or more) web font from Google Fonts, with a web-safe [CSS font stack](http://www.cssfontstack.com).
